import { G2_ASSETS } from "./assetManifest.js";

const floorDefaults = {
  kind: "floor",
  anchorX: 0.5,
  anchorY: 1,
  offsetX: 0,
  offsetY: 0,
};

const wallDefaults = {
  kind: "wall",
  layer: "wall",
  anchorX: 0.5,
  anchorY: 0.5,
  offsetX: 0,
  offsetY: 0,
  rotatable: false,
};

export const ITEM_CATALOG = [
  {
    ...floorDefaults,
    id: "coffin-bed",
    name: "Coffin Bed",
    layer: "furniture",
    type: "sleep",
    sprite: "bed",
    spriteByRotation: { 0: "bed_coffin_left", 90: "bed_coffin_right", 180: "bed_coffin_right", 270: "bed_coffin_left" },
    assetByRotation: { 0: G2_ASSETS.floor.bedCoffinLeft, 90: G2_ASSETS.floor.bedCoffinRight, 180: G2_ASSETS.floor.bedCoffinRight, 270: G2_ASSETS.floor.bedCoffinLeft },
    footprint: { w: 2, h: 3 },
    footprintByRotation: { 0: { w: 2, h: 3 }, 90: { w: 3, h: 2 }, 180: { w: 2, h: 3 }, 270: { w: 3, h: 2 } },
    colors: ["#00e5ff", "#ff2e7e", "#fcee0a"],
    rotatable: true,
    description: "A compact starter pod for crashing after long gigs.",
  },
  {
    ...floorDefaults,
    id: "mox-loveseat",
    name: "Mox Loveseat",
    layer: "furniture",
    type: "lounge",
    sprite: "seat",
    spriteByRotation: { 0: "loveseat_mox_left", 90: "loveseat_mox_right", 180: "loveseat_mox_right", 270: "loveseat_mox_left" },
    assetByRotation: { 0: G2_ASSETS.floor.loveseatMoxLeft, 90: G2_ASSETS.floor.loveseatMoxRight, 180: G2_ASSETS.floor.loveseatMoxRight, 270: G2_ASSETS.floor.loveseatMoxLeft },
    footprint: { w: 2, h: 1 },
    footprintByRotation: { 0: { w: 2, h: 1 }, 90: { w: 1, h: 2 }, 180: { w: 2, h: 1 }, 270: { w: 1, h: 2 } },
    colors: ["#ff2e7e", "#fcee0a", "#00e5ff"],
    rotatable: true,
    description: "Low seating with loud color and softer edges.",
  },
  {
    ...floorDefaults,
    id: "netrunner-rig",
    name: "Netrunner Rig",
    layer: "furniture",
    type: "work",
    sprite: "rig",
    spriteByRotation: { 0: "desk_netrunner_left", 90: "desk_netrunner_right", 180: "desk_netrunner_right", 270: "desk_netrunner_left" },
    assetByRotation: { 0: G2_ASSETS.floor.deskNetrunnerLeft, 90: G2_ASSETS.floor.deskNetrunnerRight, 180: G2_ASSETS.floor.deskNetrunnerRight, 270: G2_ASSETS.floor.deskNetrunnerLeft },
    footprint: { w: 2, h: 2 },
    footprintByRotation: { 0: { w: 2, h: 2 }, 90: { w: 2, h: 2 }, 180: { w: 2, h: 2 }, 270: { w: 2, h: 2 } },
    colors: ["#00e5ff", "#6d52ff", "#d0fdff"],
    rotatable: true,
    description: "Screens, cables, and a suspicious amount of glow.",
  },
  {
    ...floorDefaults,
    id: "biolume-plant",
    name: "Biolume Plant",
    layer: "furniture",
    type: "green",
    sprite: "plant",
    spriteByRotation: { 0: "plant_biolume_left", 90: "plant_biolume_right", 180: "plant_biolume_right", 270: "plant_biolume_left" },
    assetByRotation: { 0: G2_ASSETS.floor.plantBiolumeLeft, 90: G2_ASSETS.floor.plantBiolumeRight, 180: G2_ASSETS.floor.plantBiolumeRight, 270: G2_ASSETS.floor.plantBiolumeLeft },
    footprint: { w: 1, h: 1 },
    footprintByRotation: { 0: { w: 1, h: 1 } },
    colors: ["#42e8a4", "#b47dff", "#fcee0a"],
    rotatable: false,
    description: "A small living signal in a room full of chrome.",
  },
  {
    ...floorDefaults,
    id: "neon-lamp",
    name: "Neon Lamp",
    layer: "furniture",
    type: "lighting",
    sprite: "light",
    spriteByRotation: { 0: "lamp_floor_neon_left", 90: "lamp_floor_neon_right", 180: "lamp_floor_neon_right", 270: "lamp_floor_neon_left" },
    assetByRotation: { 0: G2_ASSETS.floor.lampFloorNeonLeft, 90: G2_ASSETS.floor.lampFloorNeonRight, 180: G2_ASSETS.floor.lampFloorNeonRight, 270: G2_ASSETS.floor.lampFloorNeonLeft },
    footprint: { w: 1, h: 1 },
    footprintByRotation: { 0: { w: 1, h: 1 } },
    colors: ["#fcee0a", "#00e5ff", "#ff2e7e"],
    rotatable: false,
    description: "A vertical glow stick for mood and drama.",
  },
  {
    ...floorDefaults,
    id: "circuit-rug",
    name: "Circuit Rug",
    layer: "floorOverlay",
    type: "floor",
    sprite: "rug",
    spriteByRotation: { 0: "rug_circuit_left", 90: "rug_circuit_right", 180: "rug_circuit_right", 270: "rug_circuit_left" },
    assetByRotation: { 0: G2_ASSETS.floor.rugCircuitLeft, 90: G2_ASSETS.floor.rugCircuitRight, 180: G2_ASSETS.floor.rugCircuitRight, 270: G2_ASSETS.floor.rugCircuitLeft },
    footprint: { w: 3, h: 2 },
    footprintByRotation: { 0: { w: 3, h: 2 }, 90: { w: 2, h: 3 }, 180: { w: 3, h: 2 }, 270: { w: 2, h: 3 } },
    colors: ["#00e5ff", "#25304a", "#ff2e7e"],
    rotatable: true,
    description: "A flat floor piece that anchors a zone.",
  },
  {
    ...floorDefaults,
    id: "compact-kitchen",
    name: "Compact Kitchen",
    layer: "furniture",
    type: "kitchen",
    sprite: "kitchen",
    spriteByRotation: { 0: "kitchen_compact_left", 90: "kitchen_compact_right", 180: "kitchen_compact_right", 270: "kitchen_compact_left" },
    assetByRotation: { 0: G2_ASSETS.floor.kitchenCompactLeft, 90: G2_ASSETS.floor.kitchenCompactRight, 180: G2_ASSETS.floor.kitchenCompactRight, 270: G2_ASSETS.floor.kitchenCompactLeft },
    footprint: { w: 2, h: 1 },
    footprintByRotation: { 0: { w: 2, h: 1 }, 90: { w: 1, h: 2 }, 180: { w: 2, h: 1 }, 270: { w: 1, h: 2 } },
    colors: ["#00e5ff", "#ff2e7e", "#11131f"],
    rotatable: true,
    description: "A compact food and caffeine station for the apartment.",
  },
  {
    ...floorDefaults,
    id: "arcade-cabinet",
    name: "Arcade Cabinet",
    layer: "furniture",
    type: "arcade",
    sprite: "arcade",
    spriteByRotation: { 0: "arcade_cabinet_left", 90: "arcade_cabinet_right", 180: "arcade_cabinet_right", 270: "arcade_cabinet_left" },
    assetByRotation: { 0: G2_ASSETS.floor.arcadeCabinetLeft, 90: G2_ASSETS.floor.arcadeCabinetRight, 180: G2_ASSETS.floor.arcadeCabinetRight, 270: G2_ASSETS.floor.arcadeCabinetLeft },
    footprint: { w: 1, h: 1 },
    footprintByRotation: { 0: { w: 1, h: 1 }, 90: { w: 1, h: 1 }, 180: { w: 1, h: 1 }, 270: { w: 1, h: 1 } },
    colors: ["#ff2e7e", "#00e5ff", "#11131f"],
    rotatable: true,
    description: "A neon cabinet for the game corner.",
  },
  {
    ...wallDefaults,
    id: "samurai-poster",
    name: "Samurai Poster",
    type: "wall",
    sprite: "poster",
    spriteByRotation: { 0: "poster" },
    assetByWall: { left: G2_ASSETS.wall.posterSamuraiLeft, right: G2_ASSETS.wall.posterSamuraiRight, front: G2_ASSETS.wall.posterSamuraiFront },
    footprint: { w: 2, h: 2 },
    wallFootprint: { w: 2, h: 2 },
    colors: ["#ff2e7e", "#11131f", "#fcee0a"],
    description: "A flat wall object that snaps to wall cells.",
  },
  {
    ...wallDefaults,
    id: "city-window",
    name: "City Window",
    type: "window",
    sprite: "window",
    spriteByRotation: { 0: "window" },
    assetByWall: { left: G2_ASSETS.wall.windowCityLeft, right: G2_ASSETS.wall.windowCityRight, front: G2_ASSETS.wall.windowCityFront },
    footprint: { w: 3, h: 2 },
    wallFootprint: { w: 3, h: 2 },
    colors: ["#00e5ff", "#202b44", "#d0fdff"],
    description: "A neon skyline window for the apartment shell.",
  },
  {
    ...wallDefaults,
    id: "rain-window",
    name: "Rain Window",
    type: "window",
    sprite: "window",
    spriteByRotation: { 0: "window" },
    assetByWall: { left: G2_ASSETS.wall.windowRainLeft, right: G2_ASSETS.wall.windowRainRight, front: G2_ASSETS.wall.windowRainFront },
    footprint: { w: 3, h: 2 },
    wallFootprint: { w: 3, h: 2 },
    colors: ["#00e5ff", "#202b44", "#d0fdff"],
    description: "Rain-lit skyline glass for noir nights.",
  },
  {
    ...wallDefaults,
    id: "holo-poster",
    name: "Holo Poster",
    type: "wall",
    sprite: "poster",
    spriteByRotation: { 0: "poster" },
    assetByWall: { left: G2_ASSETS.wall.posterHoloLeft, right: G2_ASSETS.wall.posterHoloRight, front: G2_ASSETS.wall.posterHoloFront },
    footprint: { w: 2, h: 2 },
    wallFootprint: { w: 2, h: 2 },
    colors: ["#00e5ff", "#ff2e7e", "#11131f"],
    description: "A glowing geometric wall panel.",
  },
  {
    ...wallDefaults,
    id: "wall-shelf",
    name: "Wall Shelf",
    type: "shelf",
    sprite: "shelf",
    spriteByRotation: { 0: "shelf" },
    assetByWall: { left: G2_ASSETS.wall.shelfLeft, right: G2_ASSETS.wall.shelfRight },
    footprint: { w: 3, h: 1 },
    wallFootprint: { w: 3, h: 1 },
    colors: ["#42e8a4", "#ff2e7e", "#11131f"],
    description: "A shelf for plants, shards, and tiny trophies.",
  },
  {
    ...wallDefaults,
    id: "katana-wall",
    name: "Wall Katana",
    type: "wall",
    sprite: "katana",
    spriteByRotation: { 0: "katana" },
    assetByWall: { left: G2_ASSETS.wall.katanaLeft, right: G2_ASSETS.wall.katanaRight },
    footprint: { w: 3, h: 1 },
    wallFootprint: { w: 3, h: 1 },
    colors: ["#b47dff", "#fcee0a", "#11131f"],
    description: "A dramatic wall-mounted blade.",
  },
  {
    ...wallDefaults,
    id: "neon-sign",
    name: "Neon Sign",
    type: "sign",
    sprite: "sign",
    spriteByRotation: { 0: "sign" },
    assetByWall: { left: G2_ASSETS.wall.signLeft, right: G2_ASSETS.wall.signRight, front: G2_ASSETS.wall.signFront },
    footprint: { w: 3, h: 1 },
    wallFootprint: { w: 3, h: 1 },
    colors: ["#ff2e7e", "#11131f", "#fcee0a"],
    description: "A pink hotel sign glow for the wall.",
  },
  {
    ...wallDefaults,
    id: "holo-panel",
    name: "Holo Panel",
    type: "panel",
    sprite: "window",
    spriteByRotation: { 0: "window" },
    assetByWall: { left: G2_ASSETS.wall.panelLeft, right: G2_ASSETS.wall.panelRight, front: G2_ASSETS.wall.panelFront },
    footprint: { w: 2, h: 2 },
    wallFootprint: { w: 2, h: 2 },
    colors: ["#00e5ff", "#11131f", "#6d52ff"],
    description: "A glowing diagnostics panel.",
  },
  {
    ...floorDefaults,
    id: "recon-drone",
    name: "Recon Drone",
    layer: "floating",
    type: "floating",
    sprite: "drone",
    spriteByRotation: { 0: "drone" },
    assetByRotation: { 0: G2_ASSETS.floating.drone },
    footprint: { w: 1, h: 1 },
    footprintByRotation: { 0: { w: 1, h: 1 } },
    colors: ["#ff2e7e", "#11131f", "#00e5ff"],
    rotatable: false,
    description: "A small floating apartment companion.",
  },
  {
    ...floorDefaults,
    id: "holo-clock",
    name: "Holo Clock",
    layer: "floating",
    type: "floating",
    sprite: "clock",
    spriteByRotation: { 0: "clock" },
    assetByRotation: { 0: G2_ASSETS.floating.clockHolo },
    footprint: { w: 1, h: 1 },
    footprintByRotation: { 0: { w: 1, h: 1 } },
    colors: ["#00e5ff", "#11131f", "#d0fdff"],
    rotatable: false,
    description: "A floating blue time display.",
  },
];

export function getCatalogItem(itemId) {
  return ITEM_CATALOG.find((item) => item.id === itemId) || null;
}
