export const APARTMENT_SLOTS = [
  "bed",
  "lounge",
  "desk",
  "window",
  "lighting",
  "plant",
  "decor",
  "entertainment",
  "utility",
];

// Marketplace catalog. `owned` is intentionally NOT stored here — ownership
// is player state (see apartmentState.js), not a property of the item
// definition. `allowMultiples` defaults to false; set it true for items a
// player should be able to buy more than one of (e.g. stackable decor).
export const APARTMENT_ITEMS = [
  {
    id: "coffin-bed",
    name: "Coffin Bed",
    icon: "🛏️",
    compatibleSlot: "bed",
    category: "sleep",
    rarity: "common",
    price: 140,
    vibes: { comfort: 2, tech: 1, neon: 1, rugged: 1 },
    desc: "Compact sleep pod with moody underglow.",
    allowMultiples: false,
  },
  {
    id: "mox-loveseat",
    name: "Mox Loveseat",
    icon: "🛋️",
    compatibleSlot: "lounge",
    category: "seating",
    rarity: "uncommon",
    price: 180,
    vibes: { comfort: 3, style: 3, neon: 2, cozy: 1 },
    desc: "Soft purple lounge energy with bright street attitude.",
    allowMultiples: false,
  },
  {
    id: "netrunner-rig",
    name: "Netrunner Desk",
    icon: "🖥️",
    compatibleSlot: "desk",
    category: "desk",
    rarity: "rare",
    price: 220,
    vibes: { tech: 4, neon: 1, practical: 1, corporate: 1 },
    desc: "A serious little command station for late-night ops.",
    allowMultiples: false,
  },
  {
    id: "rain-window",
    name: "Rain Window",
    icon: "🪟",
    compatibleSlot: "window",
    category: "window",
    rarity: "uncommon",
    price: 190,
    vibes: { comfort: 1, style: 2, tech: 1, cozy: 2 },
    desc: "Noir rain glass for recovery nights.",
    allowMultiples: false,
  },
  {
    id: "city-window",
    name: "City Window",
    icon: "🌃",
    compatibleSlot: "window",
    category: "window",
    rarity: "common",
    price: 160,
    vibes: { style: 2, neon: 3, cozy: 1 },
    desc: "Warm city lights without leaving the apartment.",
    allowMultiples: false,
  },
  {
    id: "neon-lamp",
    name: "Neon Lamp",
    icon: "💡",
    compatibleSlot: "lighting",
    category: "lighting",
    rarity: "common",
    price: 90,
    vibes: { neon: 4, style: 1, cozy: 1 },
    desc: "A small glow column with big room impact.",
    allowMultiples: false,
  },
  {
    id: "biolume-plant",
    name: "Biolume Plant",
    icon: "🪴",
    compatibleSlot: "plant",
    category: "greenery",
    rarity: "common",
    price: 120,
    vibes: { greenery: 4, comfort: 1, cozy: 1, practical: 1 },
    desc: "A living signal in all that chrome.",
    allowMultiples: false,
  },
  {
    id: "tarot-decor",
    name: "Tarot Decor",
    icon: "🔮",
    compatibleSlot: "decor",
    category: "occult",
    rarity: "uncommon",
    price: 135,
    vibes: { occult: 4, cozy: 1, style: 1 },
    desc: "A little mystery for the shelf.",
    allowMultiples: false,
  },
  {
    id: "samurai-poster",
    name: "Samurai Poster",
    icon: "🎴",
    compatibleSlot: "decor",
    category: "poster",
    rarity: "common",
    price: 110,
    vibes: { style: 2, neon: 2, rugged: 2 },
    desc: "Street myth on the wall.",
    allowMultiples: false,
  },
  {
    id: "music-gear",
    name: "Music Gear",
    icon: "🎸",
    compatibleSlot: "entertainment",
    category: "music",
    rarity: "uncommon",
    price: 175,
    vibes: { music: 4, style: 2, cozy: 1 },
    desc: "For late sets, quiet practice, and noisy feelings.",
    allowMultiples: false,
  },
  {
    id: "arcade-cabinet",
    name: "Arcade Cabinet",
    icon: "🕹️",
    compatibleSlot: "entertainment",
    category: "game",
    rarity: "rare",
    price: 240,
    vibes: { neon: 3, style: 2, comfort: 1, rugged: 1 },
    desc: "A glowing cabinet for downtime and bragging rights.",
    allowMultiples: false,
  },
  {
    id: "wall-shelf",
    name: "Wall Shelf",
    icon: "📚",
    compatibleSlot: "decor",
    category: "shelf",
    rarity: "common",
    price: 150,
    vibes: { comfort: 1, greenery: 1, practical: 2, cozy: 2 },
    desc: "Books, small plants, and proof someone lives here.",
    allowMultiples: false,
  },
  {
    id: "compact-kitchen",
    name: "Compact Kitchen",
    icon: "🍜",
    compatibleSlot: "utility",
    category: "practical",
    rarity: "uncommon",
    price: 210,
    vibes: { practical: 4, comfort: 1, tech: 1, corporate: 1 },
    desc: "A tiny fuel station for caffeine and noodles.",
    allowMultiples: false,
  },
  {
    id: "corporate-bar",
    name: "Corporate Bar Cart",
    icon: "🥃",
    compatibleSlot: "utility",
    category: "luxury",
    rarity: "rare",
    price: 280,
    vibes: { luxury: 4, corporate: 3, style: 1 },
    desc: "Sleek bottles, cleaner lines, dangerous hospitality.",
    allowMultiples: false,
  },
  {
    id: "training-mat",
    name: "Training Mat",
    icon: "🥊",
    compatibleSlot: "utility",
    category: "training",
    rarity: "common",
    price: 125,
    vibes: { rugged: 3, practical: 2, comfort: 1 },
    desc: "A corner for stretching, sparring, and staying sharp.",
    allowMultiples: false,
  },
  {
    id: "nomad-bunk",
    name: "Nomad Bunk",
    icon: "🏕️",
    compatibleSlot: "bed",
    category: "sleep",
    rarity: "common",
    price: 130,
    vibes: { rugged: 3, comfort: 1, practical: 1 },
    desc: "A road-worn bunk that still remembers open highway.",
    allowMultiples: false,
  },
  {
    id: "corpo-suite-bed",
    name: "Corpo Suite Bed",
    icon: "🛌",
    compatibleSlot: "bed",
    category: "sleep",
    rarity: "rare",
    price: 260,
    vibes: { luxury: 3, comfort: 2, corporate: 2 },
    desc: "Temperature-controlled sheets and a headboard that judges you softly.",
    allowMultiples: false,
  },
  {
    id: "vinyl-recliner",
    name: "Vinyl Recliner",
    icon: "🪑",
    compatibleSlot: "lounge",
    category: "seating",
    rarity: "common",
    price: 150,
    vibes: { comfort: 2, rugged: 2, style: 1 },
    desc: "Cracked leather, unreasonable comfort.",
    allowMultiples: false,
  },
  {
    id: "floor-cushion-nest",
    name: "Floor Cushion Nest",
    icon: "🧸",
    compatibleSlot: "lounge",
    category: "seating",
    rarity: "common",
    price: 130,
    vibes: { cozy: 3, comfort: 2 },
    desc: "Low to the ground and impossible to leave.",
    allowMultiples: false,
  },
  {
    id: "writers-terminal",
    name: "Writer's Terminal",
    icon: "📝",
    compatibleSlot: "desk",
    category: "desk",
    rarity: "common",
    price: 165,
    vibes: { practical: 2, cozy: 1, tech: 1 },
    desc: "A quiet corner for drafts, shards, and 2 a.m. ideas.",
    allowMultiples: false,
  },
  {
    id: "corpo-glass-desk",
    name: "Corpo Glass Desk",
    icon: "💼",
    compatibleSlot: "desk",
    category: "desk",
    rarity: "rare",
    price: 260,
    vibes: { corporate: 3, luxury: 2, style: 1 },
    desc: "Clean lines built for spreadsheets and villain monologues.",
    allowMultiples: false,
  },
  {
    id: "blackout-blinds",
    name: "Blackout Blinds",
    icon: "🪟",
    compatibleSlot: "window",
    category: "window",
    rarity: "uncommon",
    price: 150,
    vibes: { corporate: 2, practical: 2, style: 1 },
    desc: "Privacy, but make it expensive.",
    allowMultiples: false,
  },
  {
    id: "paper-lantern",
    name: "Paper Lantern",
    icon: "🏮",
    compatibleSlot: "lighting",
    category: "lighting",
    rarity: "common",
    price: 70,
    vibes: { cozy: 3, comfort: 1 },
    desc: "Soft light in a hard city.",
    allowMultiples: false,
  },
  {
    id: "trauma-team-lightbox",
    name: "Trauma Team Lightbox",
    icon: "🩺",
    compatibleSlot: "lighting",
    category: "lighting",
    rarity: "rare",
    price: 210,
    vibes: { tech: 3, neon: 2, corporate: 1 },
    desc: "Clinical glow. Probably not OSHA approved.",
    allowMultiples: false,
  },
  {
    id: "synth-fern",
    name: "Synth Fern",
    icon: "🌿",
    compatibleSlot: "plant",
    category: "greenery",
    rarity: "common",
    price: 70,
    vibes: { greenery: 3, practical: 1 },
    desc: "Nearly impossible to kill. Nearly.",
    allowMultiples: false,
  },
  {
    id: "glow-mushroom-planter",
    name: "Glow Mushroom Planter",
    icon: "🍄",
    compatibleSlot: "plant",
    category: "greenery",
    rarity: "rare",
    price: 220,
    vibes: { occult: 3, greenery: 2 },
    desc: "Technically furniture. Possibly alive.",
    allowMultiples: false,
  },
  {
    id: "wall-katana",
    name: "Wall Katana",
    icon: "🗡️",
    compatibleSlot: "decor",
    category: "wall",
    rarity: "rare",
    price: 210,
    vibes: { rugged: 3, style: 2 },
    desc: "Decorative. Probably.",
    allowMultiples: false,
  },
  {
    id: "data-shard-stack",
    name: "Data Shard Stack",
    icon: "💾",
    compatibleSlot: "decor",
    category: "shelf",
    rarity: "common",
    price: 90,
    vibes: { occult: 2, practical: 2 },
    desc: "Lore clutter. Important, probably.",
    allowMultiples: false,
  },
  {
    id: "vinyl-crate",
    name: "Vinyl Crate",
    icon: "💿",
    compatibleSlot: "entertainment",
    category: "music",
    rarity: "common",
    price: 130,
    vibes: { music: 3, cozy: 1 },
    desc: "Analog warmth for digital problems.",
    allowMultiples: false,
  },
  {
    id: "retro-console-shrine",
    name: "Retro Console Shrine",
    icon: "📺",
    compatibleSlot: "entertainment",
    category: "game",
    rarity: "uncommon",
    price: 200,
    vibes: { neon: 2, style: 2, tech: 1 },
    desc: "Couch co-op energy, permanently plugged in.",
    allowMultiples: false,
  },
  {
    id: "tea-station",
    name: "Tea Station",
    icon: "🍵",
    compatibleSlot: "utility",
    category: "practical",
    rarity: "common",
    price: 150,
    vibes: { cozy: 2, practical: 2 },
    desc: "Recovery-gig approved, kettle always warm.",
    allowMultiples: false,
  },
];

export function itemById(itemId) {
  return APARTMENT_ITEMS.find((item) => item.id === itemId) || null;
}

export function itemsForSlot(slot) {
  return APARTMENT_ITEMS.filter((item) => item.compatibleSlot === slot);
}
