// VIP roster, sourced from docs/oc-directory.md (extracted from
// docs/oc_directory.docx + docs/oc_directory2.docx — check the latter
// first, it's the more current file). All 15 known OCs are wired in here
// as of writing, but treat this as a launch roster, not a hard cap — the
// OC directory can grow. To add a new one:
//   1. Add/confirm their entry in docs/oc-directory.md.
//   2. Infer likes/dislikes/favoriteSlots from their role + traits (see the
//      archetype guidance in that doc: corporate/controlled -> luxury/tech,
//      ripperdocs -> practical/tech/comfort, musicians -> music/cozy/lounge,
//      solos -> rugged/practical, nomads -> greenery/practical/window,
//      spiritual/antique -> occult/cozy/decor).
//   3. Append a new object to VIP_VISITORS below with a unique id and four
//      short dialogue lines (loved/liked/neutral/disliked). Nothing else in
//      the app needs to change — apartmentState, visitorRating, and
//      apartmentView all iterate VISITORS generically.
export const VIP_VISITORS = [
  {
    id: "zoya-mathis",
    name: "Zoya Mathis",
    role: "Arasaka Counterintelligence",
    archetype: "Controlled Corpo Operator",
    visitorType: "vip",
    personality: "Cunning, controlled, ambitious, and difficult to read.",
    likes: ["luxury", "corporate", "tech", "style"],
    dislikes: ["cozy", "occult"],
    favoriteSlots: ["desk", "utility", "window"],
    rewardType: "xp",
    dialogue: {
      loved: "Precise. Expensive where it counts. I approve.",
      liked: "Competent arrangement. A few choices are almost elegant.",
      neutral: "Functional. Not embarrassing.",
      disliked: "I see the theory. I do not endorse the execution.",
    },
  },
  {
    id: "charlotte-santiago",
    name: "Charlotte Santiago",
    role: "Fixer",
    archetype: "Strategic Westbrook Fixer",
    visitorType: "vip",
    personality: "Measured, guarded, fair, and quietly loyal.",
    likes: ["style", "luxury", "practical", "comfort"],
    dislikes: ["rugged"],
    favoriteSlots: ["lounge", "window", "utility"],
    rewardType: "eddies",
    dialogue: {
      loved: "Good taste. Controlled, but not sterile.",
      liked: "Good bones. I can work with this.",
      neutral: "It holds together. Mostly.",
      disliked: "Too careless. Rooms talk, whether you mean them to or not.",
    },
  },
  {
    id: "emmeline-lucic",
    name: "Emmeline Lucic",
    role: "Ripperdoc",
    archetype: "Brilliant Watson Ripperdoc",
    visitorType: "vip",
    personality: "Brilliant, compassionate, erratic, and principled.",
    likes: ["practical", "tech", "comfort", "cozy"],
    dislikes: ["corporate", "luxury"],
    favoriteSlots: ["utility", "desk", "lighting"],
    rewardType: "xp",
    dialogue: {
      loved: "Oh, this works. Practical, alive, only mildly cursed.",
      liked: "Useful setup. I could patch someone here.",
      neutral: "Fine. Needs fewer gestures and more actual function.",
      disliked: "Pretty is not sterile. Or helpful. Or the point.",
    },
  },
  {
    id: "makoto-yamashiro",
    name: "Makoto Yamashiro",
    role: "Musician, DEAD AIR",
    archetype: "Private Songwriter",
    visitorType: "vip",
    personality: "Warm, observant, creative, guarded, and private.",
    likes: ["music", "cozy", "comfort", "style"],
    dislikes: ["corporate"],
    favoriteSlots: ["entertainment", "lounge", "lighting"],
    rewardType: "xp",
    dialogue: {
      loved: "This feels like somewhere a song could survive.",
      liked: "Warm. A little guarded. I like that.",
      neutral: "It is quiet enough to think in.",
      disliked: "Too managed. I can hear the walls posing.",
    },
  },
  {
    id: "maxine-lawrie",
    name: "Maxine Lawrie",
    role: "Solo",
    archetype: "Heywood Blade Solo",
    visitorType: "vip",
    personality: "Reckless, loyal, physical, stubborn, and searching.",
    likes: ["rugged", "practical", "comfort", "style"],
    dislikes: ["corporate", "luxury"],
    favoriteSlots: ["utility", "entertainment", "bed"],
    rewardType: "eddies",
    dialogue: {
      loved: "Yeah. This place can take a hit.",
      liked: "Solid. Bit pretty, but solid.",
      neutral: "It is a room. Congratulations.",
      disliked: "Too soft. I would break something by accident.",
    },
  },
  {
    id: "lukas-sayer",
    name: "Lukas Sayer",
    role: "Unlicensed Ripperdoc",
    archetype: "Kabuki Back-Room Medic",
    visitorType: "vip",
    personality: "Kind, erratic, honest, unlucky, and very tired.",
    likes: ["practical", "cozy", "comfort", "tech"],
    dislikes: ["luxury", "corporate"],
    favoriteSlots: ["utility", "lighting", "plant"],
    rewardType: "eddies",
    dialogue: {
      loved: "Kettle goes there. Chair goes there. Perfect. No notes.",
      liked: "Actually comfortable. Suspicious, but nice.",
      neutral: "Could be worse. I have slept in worse.",
      disliked: "This room has never made tea for anyone.",
    },
  },
  {
    id: "solene-rook",
    name: "Solène Rook",
    role: "Scout / Runner",
    archetype: "Aldecaldo Scout",
    visitorType: "vip",
    personality: "Patient, loyal, quiet, watchful, and direct.",
    likes: ["greenery", "practical", "comfort", "rugged"],
    dislikes: ["corporate", "luxury"],
    favoriteSlots: ["window", "plant", "utility"],
    rewardType: "eddies",
    dialogue: {
      loved: "Good air. Useful things. I could stay a while.",
      liked: "Feels honest enough.",
      neutral: "It works. I would keep the exit clear.",
      disliked: "Too polished. Nothing here knows the road.",
    },
  },
  {
    id: "juno-castellanos",
    name: "Juno Castellanos",
    role: "Antique Shop Owner / Fence",
    archetype: "Kabuki Occult Fence",
    visitorType: "vip",
    personality: "Enigmatic, intuitive, principled, private, and spiritual.",
    likes: ["occult", "cozy", "style", "comfort"],
    dislikes: ["corporate", "tech"],
    favoriteSlots: ["decor", "plant", "lighting"],
    rewardType: "eddies",
    dialogue: {
      loved: "The room has a memory. That is rare.",
      liked: "There is intention here. Keep listening to it.",
      neutral: "Some objects are still waiting to belong.",
      disliked: "Nothing here has settled. The room knows.",
    },
  },
  {
    id: "maia-huang",
    name: "Maia Huang",
    role: "Danger Gals / Puma Squad",
    archetype: "Anti-Corpo Media Merc",
    visitorType: "vip",
    personality: "Sincere, loud, warm, tactical, and anti-corporate.",
    likes: ["style", "rugged", "music", "neon"],
    dislikes: ["corporate", "luxury"],
    favoriteSlots: ["entertainment", "decor", "lighting"],
    rewardType: "xp",
    dialogue: {
      loved: "This has a point of view. Finally.",
      liked: "Loud in the right places. Respect.",
      neutral: "It is not selling me anything, so that is a start.",
      disliked: "Too branded. I can smell the handler notes.",
    },
  },
  {
    id: "elizabeth-fletcher",
    name: "Elizabeth Fletcher",
    role: "NetWatch Field Analyst",
    archetype: "Meticulous NetWatch Analyst",
    visitorType: "vip",
    personality: "Meticulous, guarded, principled, and three moves ahead.",
    likes: ["tech", "practical", "corporate"],
    dislikes: ["occult", "neon"],
    favoriteSlots: ["desk", "utility", "window"],
    rewardType: "xp",
    dialogue: {
      loved: "Every choice here justifies itself. I have no notes, which is rare.",
      liked: "Sound structure. A few decisions I would want explained, but sound.",
      neutral: "It functions. I am not going to pretend it does more than that.",
      disliked: "Something here is not accounted for. I do not like things that are not accounted for.",
    },
  },
  {
    id: "gemma-fontaine",
    name: "Gemma Fontaine",
    role: "Mox Wheelman",
    archetype: "Reckless Mox Wheelman",
    visitorType: "vip",
    personality: "Loud, loyal, reckless, and surprisingly precise.",
    likes: ["rugged", "neon", "style"],
    dislikes: ["corporate", "luxury"],
    favoriteSlots: ["utility", "entertainment", "window"],
    rewardType: "eddies",
    dialogue: {
      loved: "Okay, I am staying. Do not wait up.",
      liked: "This has teeth. I respect that.",
      neutral: "It is a room. I have crashed in worse, I have crashed in better.",
      disliked: "Too quiet in here. Makes me itch for the wheel.",
    },
  },
  {
    id: "theodore-moon",
    name: "Theodore Moon",
    role: "Late Night Host",
    archetype: "Magnetic Watson Late-Night Host",
    visitorType: "vip",
    personality: "Charismatic, generous, relentless, and quietly running on empty.",
    likes: ["music", "style", "cozy"],
    dislikes: ["corporate"],
    favoriteSlots: ["entertainment", "lounge", "lighting"],
    rewardType: "eddies",
    dialogue: {
      loved: "First place all week that does not ask anything of me. I could stay a while.",
      liked: "Warm. Genuinely. I mean that, which I do not always.",
      neutral: "Fine backdrop. I am on in five anyway.",
      disliked: "Feels like a set. I know sets.",
    },
  },
  {
    id: "vesper-nassar",
    name: "Vesper Nassar",
    role: "Freelance Tech",
    archetype: "Untethered Freelance Tech",
    visitorType: "vip",
    personality: "Inquisitive, warm, untethered, and always following the thread.",
    likes: ["tech", "practical", "greenery"],
    dislikes: ["corporate", "luxury"],
    favoriteSlots: ["desk", "window", "plant"],
    rewardType: "xp",
    dialogue: {
      loved: "Okay, tell me everything about this. Actually, everything.",
      liked: "There is a story in this room. I like that.",
      neutral: "Nothing here is asking to be understood. Fine by me, I guess.",
      disliked: "This tells me nothing about you. I do not love that.",
    },
  },
  {
    id: "evangeline-mulryan",
    name: "Evangeline Mulryan",
    role: "Bartender",
    archetype: "Hopeful Unaugmented Bartender",
    visitorType: "vip",
    personality: "Hopeful, watchful, principled, and still believing the city can be better.",
    likes: ["cozy", "comfort", "music"],
    dislikes: ["tech", "corporate"],
    favoriteSlots: ["lounge", "plant", "window"],
    rewardType: "eddies",
    dialogue: {
      loved: "This feels like somewhere good could happen. I do not say that lightly.",
      liked: "Kind room. I can feel someone tried.",
      neutral: "It is fine. I have poured drinks in worse rooms.",
      disliked: "Too cold for me. I like rooms that still believe in something.",
    },
  },
  {
    id: "clementine-roman",
    name: "Clementine Roman",
    role: "Intelligence Department, Militech",
    archetype: "Militech Intelligence Heiress",
    visitorType: "vip",
    personality: "Breezy, controlled, devoted to Militech, and unsettling with it.",
    likes: ["luxury", "corporate", "tech"],
    dislikes: ["rugged", "occult"],
    favoriteSlots: ["desk", "utility", "decor"],
    rewardType: "xp",
    dialogue: {
      loved: "Impeccable. I would almost say it flatters you, if I thought that mattered to you.",
      liked: "Tasteful. A little safe, but tasteful.",
      neutral: "It is adequate. I have seen adequate get people very far.",
      disliked: "This would not survive an audit. Neither would the excuse for it.",
    },
  },
];

// Flavor pool of generic Night City visitors. Small, easy rewards, no
// affinity tracking — these keep the apartment feeling alive between VIP
// visits. Add more the same way: id, name, role, archetype,
// visitorType: "random", four dialogue lines.
export const RANDOM_VISITORS = [
  {
    id: "kabuki-courier",
    name: "Kabuki Courier",
    role: "Courier",
    archetype: "Rain-Soaked Regular",
    visitorType: "random",
    personality: "Fast, tired, and impressed by anything with a dry chair.",
    likes: ["practical", "cozy", "neon"],
    dislikes: ["luxury"],
    favoriteSlots: ["utility", "lighting"],
    rewardType: "eddies",
    dialogue: {
      loved: "Preem stop. I almost forgot I was late.",
      liked: "Good place to catch your breath.",
      neutral: "Fine. Door works. Floor exists.",
      disliked: "No offense, but I have stairwells I like better.",
    },
  },
  {
    id: "mox-regular",
    name: "Mox Regular",
    role: "Lizzie's Regular",
    archetype: "Neon Lounge Critic",
    visitorType: "random",
    personality: "Friendly, sharp-eyed, and allergic to boring rooms.",
    likes: ["neon", "style", "comfort"],
    dislikes: ["corporate"],
    favoriteSlots: ["lounge", "lighting"],
    rewardType: "eddies",
    dialogue: {
      loved: "Cute. Dangerous. Love the glow.",
      liked: "You have taste. Keep going.",
      neutral: "Needs a little more pulse.",
      disliked: "Where is the fun supposed to happen?",
    },
  },
  {
    id: "aldecaldo-runner",
    name: "Aldecaldo Runner",
    role: "Runner",
    archetype: "Badlands Drop-Off",
    visitorType: "random",
    personality: "Practical, road-worn, and direct.",
    likes: ["rugged", "practical", "greenery"],
    dislikes: ["corporate"],
    favoriteSlots: ["window", "utility"],
    rewardType: "eddies",
    dialogue: {
      loved: "Useful setup. Good instincts.",
      liked: "Not bad for city walls.",
      neutral: "It will do.",
      disliked: "Too sealed up. Makes my teeth itch.",
    },
  },
  {
    id: "afterlife-bartender",
    name: "Afterlife Bartender",
    role: "Bartender",
    archetype: "Quiet Reputation Reader",
    visitorType: "random",
    personality: "Calm, observant, and impossible to impress loudly.",
    likes: ["style", "luxury", "music"],
    dislikes: ["rugged"],
    favoriteSlots: ["lounge", "entertainment"],
    rewardType: "xp",
    dialogue: {
      loved: "Good atmosphere. People would talk here.",
      liked: "Nice balance. Not trying too hard.",
      neutral: "I have seen worse booths.",
      disliked: "No mood. No story.",
    },
  },
  {
    id: "street-netrunner",
    name: "Street Netrunner",
    role: "Netrunner",
    archetype: "Sidewalk Signal Hunter",
    visitorType: "random",
    personality: "Wired, impatient, and fond of clean signal.",
    likes: ["tech", "neon", "practical"],
    dislikes: ["occult"],
    favoriteSlots: ["desk", "lighting"],
    rewardType: "xp",
    dialogue: {
      loved: "Signal is clean. I could work here.",
      liked: "Nice tech stack.",
      neutral: "Passable bandwidth energy.",
      disliked: "Too much weird, not enough useful.",
    },
  },
  {
    id: "tired-medtech",
    name: "Tired Medtech",
    role: "Medtech",
    archetype: "End-of-Shift Visitor",
    visitorType: "random",
    personality: "Gentle, exhausted, and deeply pro-comfort.",
    likes: ["comfort", "practical", "greenery"],
    dislikes: ["luxury"],
    favoriteSlots: ["bed", "plant"],
    rewardType: "eddies",
    dialogue: {
      loved: "This lowers my blood pressure. Keep it.",
      liked: "Restful. That is rarer than it should be.",
      neutral: "Usable. Needs a softer landing.",
      disliked: "My shift room has better vibes, and that is grim.",
    },
  },
];

export const VISITORS = [...VIP_VISITORS, ...RANDOM_VISITORS];

export function visitorById(visitorId) {
  return VISITORS.find((visitor) => visitor.id === visitorId) || VISITORS[0];
}
